### ISSUE TITLE
If a GPU already exists in the database, the entry is stuck with the Vulkan/OpenGL version of the uploader

### ISSUE THREAD

**Issue by starks** [SaschaWillems/vulkan.gpuinfo.org#1]
This doesn't make sense to me given how quickly Vulkan is evolving and version-bumping.

A GPU that was uploaded with version 1.0.8 will not be updated to reflect that it is now capable of 1.0.37.

**Comment by SaschaWillems** [comment]
Can you be a bit more specific? If API version support changes then the driver version of that GPU should change too, and that's one of the aspects that's compared. So if a GPU has a report for API Version 1.0.37 with driver 1.0 and the next driver is 1.1 that supports 1.0.38 then you can submit a new report. So what you're telling would only apply to a GPU/device where the IHV does not increase/change driver version.

**Comment by starks** [comment]
What I'm getting at is that there is no option to upload a new report if the GPU already exists in the database.

**Comment by SaschaWillems** [comment]
A forced upload does not make sense (if there are no changes). Right now for Vulkan these are the primary keys that decide on whether a new report (for an existing GPU) can be resubmitted:
- Device name
- Driver version
- Operating system (name, version, arch)

The client application currently does not take the API level into account, and by your description that's whats actually missing? If that's the case can you open an issue at the repo for the client application (https://github.com/SaschaWillems/VulkanCapsViewer)? I'll be releasing an update to the caps viewer soon and this is something I could quickly implement if request.
