### ISSUE TITLE
Incorrect implied requirements for limits.

### ISSUE THREAD

**Issue by TiemoJung** [SaschaWillems/vulkan.gpuinfo.org#10]
Hi,

just stumbled over maxDrawIndexedIndexValue limit and the implied requirement of fullDrawIndexUint32, which is incorrect. First, logically it makes no sense to have this value if the device supports full 32bits, it can be only one value and the data in maxDrawIndexedIndexValue is only valuable if fullDrawIndexUint32 is not supported. Also the spec does not imply a requirement, see https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#features-features-fullDrawIndexUint32

May be other values are affected too, but just found this for now.
(The implied requirement should, if applied, be inverted)

**Comment by SaschaWillems** [comment]
I have completely removed those limit displays. Imo they don't belong in the database.
