### ISSUE TITLE
Diagonal Headers Instead of Vertical on Tables

### ISSUE THREAD

**Issue by burak-efe** [SaschaWillems/vulkan.gpuinfo.org#101]
Example:
![45-deg](https://github.com/user-attachments/assets/0a4dcfd8-8618-4482-a58b-982ae27d4aa8)

this would make much easier to read those headers

**Comment by SaschaWillems** [comment]
I actual had that at some point, but decided not to do this. They look nice with evenly large and mostly short titles, but don't work well with the database. They also add a lot of empty space right-hand.
