### ISSUE TITLE
Improve readability on high-res monitos & dark mode

### ISSUE THREAD

**Issue by jherico** [SaschaWillems/vulkan.gpuinfo.org#109]
I'm not sure what styling is responsible for this, but on my primary monitor, a 27 inch monitor running at 1440 resolution, this is how the queue families page for a given card renders for me.

![image](https://github.com/user-attachments/assets/6199bb07-5f25-417d-a3a1-e29726d928d6)

The combination of the rotated text, the relatively low contrast of red on gray coloring and the font size conspire to make this nearly impossible for me to read unless I manually zoom the page in quite a bit.  

Opening up the developer tools for the page, it looks like the text is specified at 10px and the height of the header control at 400px, but I get much better results if I tweak these values to be relative to the view height, using `1.25vh` and `25vh` respectively.  

The dev tools in chrome also indicate that the color being used `#a31d1d` has a contrast ratio against the background of 2.28, which is significantly below the minimum and recommended values of 4.5 and 7.0.  The background color seems to be dervied from `--backgroundcolor-full` in the style.css`.  Making the background color darker, or the text a different hue, or increasing the text brightness all improve the readability of the text dramatically.

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. Will fix adjust this with one of the upcoming updates.

**Comment by SaschaWillems** [comment]
Sorry for the late reply. I have replaced the dark red with a brighter (almost white) gray and also moved the captions a bit so they don't overlap with the sort icons:

![image](https://github.com/user-attachments/assets/2cf5c6b3-04ef-49bb-9f6d-5c6c610a372d)

Still not optimal but hopefully easier to read.
