### ISSUE TITLE
'Latest Driver Version' column incorrectly decoded

### ISSUE THREAD

**Issue by scyganINTEL** [SaschaWillems/vulkan.gpuinfo.org#12]
The 'Latest Driver Version' column on pages like: 
https://vulkan.gpuinfo.org/listdevices.php?platform=windows&extension=VK_KHR_uniform_buffer_standard_layout

.. does not decode (Intel) driver versions correctly.

For example, on above page, the version is given as `0.401.3010`.  However, when clicking on device name, the device page already show proper version (100.6xxx).

**Comment by SaschaWillems** [comment]
Can you check again? I've just pushed an update to the database that should include a fix for this.

**Comment by scyganINTEL** [comment]
Thank You! 

It's displayed correctly now.
