### ISSUE TITLE
Update the title

### ISSUE THREAD

**Issue by FichteFoll** [SaschaWillems/vulkan.gpuinfo.org#14]
It would be nice if the website didn't show "Vulkan Hardware Database by Sascha Willems" for every single page and instead indicated what kind of subpage it is or most notably which card's data you're looking at currently. This would greatly help nagivation across multiple tabs.

**Comment by SaschaWillems** [comment]
That's actually a great idea. I'll add this for the next big update which is hopefully soon.

**Comment by SaschaWillems** [comment]
The update including this change is now live.

**Comment by FichteFoll** [comment]
Perfect :+1:
