### ISSUE TITLE
Detailed Format Information

### ISSUE THREAD

**Issue by ghost** [SaschaWillems/vulkan.gpuinfo.org#18]
The online database, http://vulkan.gpuinfo.org, does not show the detailed format information which is displayed by the vulkaninfo.exe tool. It would be nice to also be able to see this online.

One usage case for this is to easily be able to figure out what different vendors support beyond the mobile-friendly baseline support described here,

https://vulkan.lunarg.com/doc/view/1.0.26.0/linux/vkspec.chunked/ch31s03.html#features-required-format-support

The specific case which prompted this issue was getting general vendor visibility on if R8_UNORM and R16_UNORM is supported in optimalTiling for VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT for compute shaders writing to single-channel textures.

**Comment by kainino0x** [comment]
FYI, the WebGPU community group would find this info incredibly useful, e.g. https://github.com/gpuweb/gpuweb/issues/652

**Comment by SaschaWillems** [comment]
A new update has been released with detailed format listings.
