### ISSUE TITLE
Invalid reports in the database

### ISSUE THREAD

**Issue by NicolBolas** [SaschaWillems/vulkan.gpuinfo.org#19]
The database contains a number of reports that are invalid, with regard to the spec thanks to beta Vulkan drivers.

This is particular pernicious in the Limits section. For example, Vulkan requires that implementations specify that `maxPerStageDescriptorSamplers` be at least 16. However, if you look at the database, a couple of entries specify 0. Indeed, thanks to such reports, the [entire Limits page](http://vulkan.gpuinfo.org/listlimits.php) has 0 for the minimum value.

Reports from dysfunctional implementations limit the usefulness of the database. I would suggest adjusting the Caps viewer to at least check the reported limits against the minimum requirements (a non-trivial task, since many limits are based on support for one or more features).

Oh, and it would be good if the website, when generating that Limits page, could ignore values from implementations that don't support that feature. For example, `maxTessellationGenerationLevel` is allowed to be 0 if the tessellation feature isn't supported. But I don't really care about what the smallest supported max tessellation level is for hardware that _doesn't support it_. I want to see what the smallest supported maximum is for hardware that actually supports it. Again, a non-trivial task, to be sure.

**Comment by SaschaWillems** [comment]
I'm preparing for a big update and have removed lots of invalid and wrong reports, so they no longer affect correctness of the displayed data.
