### ISSUE TITLE
Column "Latest driver version" actually shows highest known version number

### ISSUE THREAD

**Issue by StefanG3D** [SaschaWillems/vulkan.gpuinfo.org#21]
Many NVIDIA GPUs show 450.12, but e.g. 442.37 is a later driver.

In spite of advertising _unified driver architecture_, NVIDIA is suffering from "branchitis" and there seems to be no cure in sight :P

**Comment by SaschaWillems** [comment]
Is this an error in the database? If it's about NVIDIA having features in different branches, that's sadly nothing I can do about.

**Comment by krOoze** [comment]
Probably insider drivers?

**Comment by SaschaWillems** [comment]
Yes, that seems to be an insider driver. But it's not uncommon for such big software project's as drivers to have different branches. As this is not related to my database I'll close it.
