### ISSUE TITLE
 device properties vendorIDs not displayed, for unknown vendors

### ISSUE THREAD

**Issue by baryluk** [SaschaWillems/vulkan.gpuinfo.org#28]
It appears that the vulkan.gpuinfo.org site tries to interpret vendorID and map it using maybe PCI-SIG database of vendor IDs, or a short list of known common IDs.

But, for ones that are not recognized, it doesn't display it at all.

https://www.vulkan.gpuinfo.org/displayreport.php?id=10043

This should display 0x10005   (it is actually registered Khronos Vulkan Vendor ID, but that is beside the point).

But it doesn't.

In the json file, you can find it is there: `"vendorID": 65541`

The vendorID does display in the application itself correctly, as 0x1005

**Comment by SaschaWillems** [comment]
Vendor IDs are matched from a database table, so for vendors not getting display, I need to know the ID and the vendor name and I can add it to that table. From this issue it's not clear what vendor name belongs to the vendorID 0x10005. So if you could add the name that belongs to this ID I can add it to the database.

**Comment by baryluk** [comment]
It is Mesa.

I still think, it would make sense to display just the number for the IDs you don't know.

Vendor IDs above 0xFFFF are usually registered at Khronos. The 0x0000 - 0xFFFF are usually registered using PCI-SIG and match PCI vendor IDs, or USB vendor IDs.

**Comment by SaschaWillems** [comment]
Fixed. Mesa was added to the vendor mapping table, and for vendors not yet present in that table, the database will just display the vendor ID.

**Comment by baryluk** [comment]
Thank you!
