### ISSUE TITLE
Doesn't list instance extensions

### ISSUE THREAD

**Issue by haasn** [SaschaWillems/vulkan.gpuinfo.org#3]
I'm trying to find out which enviroments support e.g. VK_EXT_swapchain_colorspace, but this is not possible with `vulkan.gpuinfo.org` since it seems to omit instance extensions.

A separate category for these would be great. (Note: It might be a good idea to separate them out from the device reports, because they can be influenced by multiple installed ICDs)

**Comment by krOoze** [comment]
It seems to have been implemented: https://vulkan.gpuinfo.org/listinstanceextensions.php
