### ISSUE TITLE
Adreno devices missing from the web front-end

### ISSUE THREAD

**Issue by lmveilleux** [SaschaWillems/vulkan.gpuinfo.org#30]
Hello,

Adreno 6xx, Samsung Galaxy S10 and presumably other devices which used to be listed are no longer listed at https://vulkan.gpuinfo.org/.

![image](https://user-images.githubusercontent.com/7597015/102517245-d08d7600-405d-11eb-8f4d-cb9810d57796.png)

![image](https://user-images.githubusercontent.com/7597015/102517324-e602a000-405d-11eb-8b22-c2eaf415dfe0.png)

Tested with Chrome and Edge, from 2 different Windows PCs. The 'Could not fetch data (error)' was displayed in some tests but not in others, and the mentioned devices were missing regardless of whether that error message was displayed or not.

Thanks

**Comment by SaschaWillems** [comment]
Thanks for noticing. They are listed on the reports listing. I recently had to rework some parts of the database regarding Android device naming, so this is probably a result of that. Will take a look at this.

**Comment by lmveilleux** [comment]
I'm not sure they showed up as "Galaxy S10" before or if their internal names were used. We could find them by GPU Name though, as you mentioned.

I did manage to find the report I was looking for using the device internal name, thanks.
