### ISSUE TITLE
XSS vulnerability on listdevices.php

### ISSUE THREAD

**Issue by maple3142** [SaschaWillems/vulkan.gpuinfo.org#35]
Example: https://vulkan.gpuinfo.org/listdevices.php?extension=%27%2Balert(1)%2B%27

**Comment by SaschaWillems** [comment]
Thanks for letting me know. I guess this applies to other views too. Will take a look it.

**Comment by SaschaWillems** [comment]
(Hopefully) fixed in all critical spots with today's update.
