### ISSUE TITLE
Aggregate swapchain colorspaces

### ISSUE THREAD

**Issue by nanokatze** [SaschaWillems/vulkan.gpuinfo.org#38]
Currently, https://vulkan.gpuinfo.org/listsurfaceformats.php only aggregates surface formats, but surface format × color space tuples are nowhere to be found. This would help with getting rough idea about what kind of other-than-8-bit-SDR-capable configurations are out in the wild.

**Comment by SaschaWillems** [comment]
That makes sense. I'll incorporate that into the next release.

**Comment by SaschaWillems** [comment]
Released with today's update.
