### ISSUE TITLE
Wrong extension when selecting listing for duplicate property names

### ISSUE THREAD

**Issue by fxshlein** [SaschaWillems/vulkan.gpuinfo.org#39]
Hi!

When I click on "Listing" for a Property on https://vulkan.gpuinfo.org/listpropertiesextensions.php I get redirected to `https://vulkan.gpuinfo.org/displayextensionproperty.php?name=(PROPERTY NAME)&platform=windows` (with the correct property name of course).

This does work for unique property names, but for property names that exist in multiple extensions (for example `maxInstanceCount`, which exists in `VK_KHR_acceleration_structure`, `VK_KHR_ray_tracing` and `VK_NV_ray_tracing`) the opened page has no knowledge of which extension to display the property for and just selects one (`VK_NV_ray_tracing` in this case).

**Comment by SaschaWillems** [comment]
Thanks for raising this issue. I'll try to incorporate a fix for this into the next release.

**Comment by SaschaWillems** [comment]
Fixed with  today's update.
