### ISSUE TITLE
Report ycbcr formats

### ISSUE THREAD

**Issue by djdeath** [SaschaWillems/vulkan.gpuinfo.org#4]
I was looking at the list of supported formats, but I can't find the ycbcr ones 
 (starting at VK_FORMAT_G8B8G8R8_422_UNORM in https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#VkFormat)

**Comment by SaschaWillems** [comment]
Yes, the newer formats are still missing. I plan on adding these in a future update.

**Comment by djdeath** [comment]
Thanks!

**Comment by SaschaWillems** [comment]
Those formats have been added some time ago and are present in the database.
