### ISSUE TITLE
Recent update seems to have broken viewing format support table on Chrome.

### ISSUE THREAD

**Issue by alister-chowdhury** [SaschaWillems/vulkan.gpuinfo.org#42]
Hi there,

It seems there was a recent update which changed the way format support is rendered.

Unfortunately it seems to not be compatible with chrome (92.0.4515.107 on Windows 10):
![numbers](https://user-images.githubusercontent.com/30833607/127814397-9e8b52c1-f18c-4ee6-9046-4673bf9809f7.png)

I had a cheeky look the console log and saw:
```js
Uncaught TypeError: Cannot read property 'display' of undefined
    at responsive.bootstrap.min.js:5
    at responsive.bootstrap.min.js:5
    at responsive.bootstrap.min.js:5
```

Which seems imply something to do with data tables.

Additionally, it was handy before to be able to sort entries by percentage rather than name (for weighing up what formats you would support), which seems to no longer be an option :(

Many thanks,
Alister

**Comment by SaschaWillems** [comment]
This looks like the stylesheet hasn't been refreshed. Can you do a proper clean reload of the page (CTRL+F5 should suffice)? I use the exact same combo of Windows 10 and Chrome and it works fine. Chrome may cache the stylesheet though, so a forced refresh should work.

As for the missing sorting: I'll add it back once I figured out how to properly make it work with rotated headers.

**Comment by alister-chowdhury** [comment]
Aha!
This worked a treat! Many thanks!

Good to hear about the sorting too!

**Comment by SaschaWillems** [comment]
Adding sorting back to the rotated header was easier than thought. If you refresh the page again sorting should be there.

**Comment by alister-chowdhury** [comment]
Oh that's so awesome!
Works fantastic!
