### ISSUE TITLE
Tables showing format support incorrectly?

### ISSUE THREAD

**Issue by Tobski** [SaschaWillems/vulkan.gpuinfo.org#43]
Looking at the format support for [this report](https://vulkan.gpuinfo.org/displayreport.php?id=12509#formats) on the website shows that R64_UINT has no support - which seemed wrong, as that report also advertises VK_EXT_shader_image_atomic_int64, which requires it. Taking a look at the JSON file, it seems that format 110 (R64_UINT) actually _does_ show the correct required bits here -  it's just that the website isn't showing it.

**Comment by SaschaWillems** [comment]
What type where you looking at? Linear or [optimal image tiling](https://vulkan.gpuinfo.org/displayreport.php?id=12509#formats_optimal)? It shows up as supported for the latter, which seems correct.

**Comment by Tobski** [comment]
Ick, looks like I was looking at linear tiling - didn't even see the tab. Does it default to linear?

**Comment by SaschaWillems** [comment]
Yeas, linear is the first tab when you navigate to the formats. It may not be the best solution. Do you think it would make more sense to have optimal tiling formats as the first tab?

**Comment by Tobski** [comment]
Yea, I think most people pay more attention to the optimal formats since these are _generally_ what developers are using. Certainly tripped me up 😅
