### ISSUE TITLE
Wrong GPU info uploaded by accident.

### ISSUE THREAD

**Issue by jiaxiongjiao** [SaschaWillems/vulkan.gpuinfo.org#44]
Hi, I accidentally used Wayland version of the software to upload my GPU info on linux instead of X11. Thus, it shows this gpu has no surface info and present queue is not supported. Is there any way to re-upload or change this? On X11 version of the software, this gpu's surface info is shown correctly and present queue is supported.

Sorry about the inconvenience.

Info for that submission:

Device Name: Intel(R) HD Graphics 6000 (BDW GT3)
Submitted By: JiaxiongJiao
Submitted At: 2021-12-11 06:09:00

**Comment by SaschaWillems** [comment]
If you post the id or the link to that report, I can remove it and you can reupload.

**Comment by jiaxiongjiao** [comment]
https://vulkan.gpuinfo.org/displayreport.php?id=13367

**Comment by SaschaWillems** [comment]
I have removed that report. You should be able to reupload again.

**Comment by jiaxiongjiao** [comment]
Done. Thank you!
