### ISSUE TITLE
Reports listed as not supporting `customBorderColorWithoutFormat` actually support it

### ISSUE THREAD

**Issue by ShabbyX** [SaschaWillems/vulkan.gpuinfo.org#51]
Looking at https://vulkan.gpuinfo.org/listfeaturesextensions.php for `customBorderColorWithoutFormat`, it lists ~75% of reports not supporting it. I clicked through a few of them and downloaded the full report, only to find out `customBorderColorWithoutFormat` is actually true in those reports. Take this for example: https://vulkan.gpuinfo.org/displayreport.php?id=15142

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. As you noticed, those numbers are off, esp. on Android.

**Comment by ShabbyX** [comment]
Ah, it seems like the UI fooled me. I see now for example this in the list that supports the feature:

```
Google Pixel 6	ARM	32.1.0
```

But then clicking on `Google Pixel 6` brings up another list that actually has different driver versions. I must have clicked on one with a different driver. I probably assumed that clicking on `Google Pixel 6` must give me the relevant reports (conditioned to the driver version specified there) rather than all reports.

**Comment by SaschaWillems** [comment]
That's true. The user interface is a bit misleading in such cases, esp. on mobile where driver numbers are all over the place, and where a higher driver number doesn't mean it has more features than lower versions.

I'll try to come up with a more intuitive way.

**Comment by SaschaWillems** [comment]
I have reworked how filtering works in the database, so now clicking on the list you only get the reports (and driver versions) that actually support the requested feature, see https://vulkan.gpuinfo.org/listreports.php?devicename=Google+Pixel+6&extensionname=VK_EXT_custom_border_color&extensionfeature=customBorderColorWithoutFormat&platform=android
