### ISSUE TITLE
Display GPU names in Android listings

### ISSUE THREAD

**Issue by SaschaWillems** [SaschaWillems/vulkan.gpuinfo.org#55]
The Android listings show device names. This makes sense, as the same GPU may have different capabilities for different devices due to how vendors distribute drivers.

It would be beneficial though if people could still filter by GPU names, so you can find all devices that use a certain GPU type.

**Comment by hrydgard** [comment]
Sorry to bump a thread, but I was just gonna file an issue about this and found this one. As a maintainer of a popular Vulkan app for Android, this would be immensely, incredibly useful when trying to figure out for example what driver versions for a Mali-T880 are out there, and a lot of other use cases.

Do you already separately collect this information so it could be made available?

While I'm at it, being able to simply filter on GPU vendor on this view would be useful: https://vulkan.gpuinfo.org/listdevices.php?platform=android

It's very strange that on this view you can filter and sort on driver version, without first being able to filter on GPU vendor...

**Comment by SaschaWillems** [comment]
Android is complicated. I only displayed GPU names on Android in the first place, but then people wanted to find Android devices by their product names, so I changed that. It's hard to please everybody ;)

To please both target audiences I now also display the GPU name on the Android device listing:

![image](https://user-images.githubusercontent.com/10283127/236620182-a559c5fd-df59-4233-866b-ea2004fd7848.png)

Does that work for you?

**Comment by hrydgard** [comment]
That's fantastic, exactly what I want!

Really, that should indeed please everybody - I can't imagine there are actually people who want to see only the GPU and definitely not the device name, or people who only want to see the device name but definitely not the GPU.
