### ISSUE TITLE
incorrect report

### ISSUE THREAD

**Issue by endim8** [SaschaWillems/vulkan.gpuinfo.org#56]
not sure if this is the right place, but i can't find anywhere else, sorry

this report is assigned to the oneplus 8pro, but the actual stats seem to represent a poco x3
https://vulkan.gpuinfo.org/displayreport.php?id=11615

**Comment by endim8** [comment]
I didn't make it I'm afraid, just came across it

**Comment by SaschaWillems** [comment]
There's probably nothing I can do about it. A similar report was uploaded recently with a comment that the device name was spoofed. I have no way to contact the uploader, and unless this is really a wrong report there's not much than I can do except for deleting it.
