### ISSUE TITLE
Incorrect report: deviceName should be AMD Radeon RX 6500M

### ISSUE THREAD

**Issue by Thymelizabeth** [SaschaWillems/vulkan.gpuinfo.org#57]
This is the report: [https://vulkan.gpuinfo.org/displayreport.php?id=18379](https://vulkan.gpuinfo.org/displayreport.php?id=18379)

It has the device name as `AMD Radeon RX 6500` when there is no such graphics card listed on the AMD website.

**Comment by SaschaWillems** [comment]
I display the names that I get from the driver. Can you check what display name is shown in the Vulkan Hardware Capability Viewer client application?

But just looking at it this is probably something that needs to be fixed in the driver. On Windows the "M" is properly added to the device name.

**Comment by Thymelizabeth** [comment]
In the application it shows `AMD Radeon RX 6500`.

When I run `vulkaninfo` it shows the same thing.

**Comment by SaschaWillems** [comment]
Then you need to contact your device vendor to fix this. The application (and database) just take what's reported by the driver.
