### ISSUE TITLE
maxComputeWorkGroupSize is not being dumped in the JSON

### ISSUE THREAD

**Issue by spencer-lunarg** [SaschaWillems/vulkan.gpuinfo.org#58]
It seems currently any JSON file downloaded is not showing the `maxComputeWorkGroupSize` anymore in 

```
"capabilities": {
    "device": {
        "properties": {
                "limits": {
```

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. Looks like I missed to remap the database structure to the profile JSON structure. Just pushed a fix for it.
