### ISSUE TITLE
Don't show Queue Families that don't really exist

### ISSUE THREAD

**Issue by spencer-lunarg** [SaschaWillems/vulkan.gpuinfo.org#59]
https://vulkan.gpuinfo.org/displayreport.php?id=1999#queuefamilies

is any example of a Queue Family with 0 `Queue count` and I am not sure, but seems this was added by accident. Not sure if you have a "clean up" pass for things like this

**Comment by SaschaWillems** [comment]
I do have means of cleaning up, but it just looks like this device and driver combination just reported this wrong.
