### ISSUE TITLE
When you compare graphics card limits are wrong highlighted

### ISSUE THREAD

**Issue by mercuriete** [SaschaWillems/vulkan.gpuinfo.org#6]
Description:
When you compare two graphics card on vulkan gpuinfo, the limits are highlighted on black if is better and red if is worse.
But if the more negative is better is still red.

Steps to reproduce:
1) goto: https://vulkan.gpuinfo.org/compare.php?compare=compare&id%5B3647%5D=on&id%5B3646%5D=on
2) goto limits tab
3) goto minTexelOffset
4) check the numbers -> -8 and -32

Actual results:
-8 is black but -32 is red

Expected results:
-32 is bigger than -8 so. -32 should be black and -8 should be red.

Same issue for:
minUniformBufferOffsetAlignment
values are 32 and 4. I think 4 is better than 32.

Thanks for this awesome tool.

**Comment by SaschaWillems** [comment]
This has been fixed, and will be released with the next big update.
