### ISSUE TITLE
No VkPhysicalDeviceSubgroupProperties reported in JSON Profile

### ISSUE THREAD

**Issue by spencer-lunarg** [SaschaWillems/vulkan.gpuinfo.org#62]
Vulkan 1.1 released a `VkPhysicalDeviceSubgroupProperties` (values also in `VkPhysicalDeviceVulkan11Properties`) but the data are not dumped in the JSON (but are visible on the website)

**Comment by SaschaWillems** [comment]
Can you link to a report, or does this affect all reports? If so I'll have to take a look into how I map that structure to the JSON schema file.

**Comment by spencer-lunarg** [comment]
https://vulkan.gpuinfo.org/displayreport.php?id=15189

should have

```json
                "VkPhysicalDeviceSubgroupProperties": {
                    "subgroupSize": 64,
                    "supportedStages": [
                        "VK_SHADER_STAGE_COMPUTE_BIT"
                    ],
                    "supportedOperations": [
                        "VK_SUBGROUP_FEATURE_BASIC_BIT",
                        "VK_SUBGROUP_FEATURE_VOTE_BIT",
                        "VK_SUBGROUP_FEATURE_ARITHMETIC_BIT",
                        "VK_SUBGROUP_FEATURE_BALLOT_BIT",
                        "VK_SUBGROUP_FEATURE_SHUFFLE_BIT",
                        "VK_SUBGROUP_FEATURE_SHUFFLE_RELATIVE_BIT"
                    ],
                    "quadOperationsInAllStages": false
                },
```

notes that might be source of issue
- This struct was added in 1.1 as a special thing, there was no extension tied to it (same with `VkPhysicalDeviceProtectedMemoryProperties`) 
-  the variable names in `VkPhysicalDeviceVulkan11Properties` are slightly different

**Comment by SaschaWillems** [comment]
I'm now manually adding that struct to profile generation. Please check again.
