### ISSUE TITLE
Supported Devices Does Not Include AMD Radeon Graphics APUs

### ISSUE THREAD

**Issue by FatalSleep** [SaschaWillems/vulkan.gpuinfo.org#65]
List of supported devices does not include AMD Radeon 3, 5 & 7 Graphics APUs:

https://www.amd.com/en/processors/ryzen-with-graphics#Model-Specifications

**Comment by SaschaWillems** [comment]
Can you elaborate? The database is based on user submissions, and I'm pretty sure that there are reports for AMD's APUs, e.g. https://vulkan.gpuinfo.org/displayreport.php?id=19786.

How the devices identify themselves is up to the vendor though, and nothing I can influence.

**Comment by FatalSleep** [comment]
Ah the listing is generic under AMD Radeon Graphics. No wonder, in that case that makes sense since both AMD/Intel don't differentiate between their iGPU models specifically. Problem solved.
