### ISSUE TITLE
DriverVersion not reported correctly for recent Qualcomm uploads

### ISSUE THREAD

**Issue by jackohound** [SaschaWillems/vulkan.gpuinfo.org#7]
Recent uploads for Qualcomm Adreno have an incorrect version reported on the web site.  For example:
the report I submitted [report 3765](https://vulkan.gpuinfo.org/displayreport.php?id=3765) displayed driver version 512.313.0 in VulkanCapsViewer.  This is the correct version as our Andorid-P drivers have switched to Vukan API-like encoding of driver version.  Howerver, on the web site it shows 511.1023.4095.  The version in the JSON download correctly matches the 512.313.0 version:
>  "driverVersion": 2148765696,

I looked though some of the sources in this repo but couldn't figure out by inspection where the  511.1023.4095 version is coming from.

**Comment by SaschaWillems** [comment]
Looks like I fixed this more ore less accidently at some point. The website also shows 512.313.0 for that device.
