### ISSUE TITLE
Request:add reporting for mesh and task shader in subgroupSupportedStages in vulkan.gpuinfo.org

### ISSUE THREAD

**Issue by oscarbg** [SaschaWillems/vulkan.gpuinfo.org#70]
Hi,

this is not a bug of vulkancapsviewer app (as it shows task_bit as mesh_bit correctly)..
but a request to expose on vulkan.gpuinfo.org on the properties/Core1.1/subgroupSupportedStages also task and mesh shader support..

I have almost two identical lavapipe reports except one "expose subgroups in mesh/task shaders" via this commit:
"lavapipe: expose subgroups in mesh/task shaders"
https://cgit.freedesktop.org/mesa/mesa/commit/?id=832c408b63f5ef24fbb1d4bd9e1934c253a22799
so one is
 "subgroupSupportedStages": 48
another is
 "subgroupSupportedStages": 240
comparing reports at:
http://vulkan.gpuinfo.org/compare.php?reports=22371,22272#properties_core_11
doesn't allow to see any difference while one has task mesh support..

thanks..

**Comment by SaschaWillems** [comment]
I have added the new flags, they should now properly show up.

**Comment by oscarbg** [comment]
Thanks!
