### ISSUE TITLE
Lack of clarification regarding sourcing of data

### ISSUE THREAD

**Issue by tecanec** [SaschaWillems/vulkan.gpuinfo.org#73]
I'm the kind of guy who can't really trust information without knowing how it got there, and I feel like that's not really clear enough with this (otherwise very useful) database. There are a few things that I feel like I should know:

- How are the examinees chosen? Whether the examinees are mostly other developers who know about the dataset and want to contribute, or completely random people found by an otherwise unrelated service, could make a huge difference in accuracy. 
- How regularly are old data discarded? When the dataset says that this really useful extension only has 50% availabillity, is that actually accurate today or does that include samples from before the extension was even released?
- What even is 50%? Let's say someone's PC has both a high-end discrete GPU with all the latest features and a low-end integrated GPU with only the most basic features. Is only the most powerful GPU chosen, or does that person get two conflicting votes? Or is the maximum chosen between each GPU in the same machine?

Knowing this kind of stuff lets us look at the data more critically, which greatly increases its value. This is not a request to correct or alter the data itself, only to let us know how to most accurately interpret it.

**Comment by SaschaWillems** [comment]
> How are the examinees chosen? Whether the examinees are mostly other developers who know about the dataset and want to contribute, or completely random people found by an otherwise unrelated service, could make a huge difference in accuracy.

Anyone can use the client application to upload data. It's mostly aimed at developers though.

> How regularly are old data discarded? When the dataset says that this really useful extension only has 50% availabillity, is that actually accurate today or does that include samples from before the extension was even released?

I don't discard data unless it's faulty. Calculations like coverage is based on most recent data, so old data doesn't influence coverage. 50% coverage means that 50% of the devices submitted to the database currently support that extension.

> What even is 50%? Let's say someone's PC has both a high-end discrete GPU with all the latest features and a low-end integrated GPU with only the most basic features. Is only the most powerful GPU chosen, or does that person get two conflicting votes? Or is the maximum chosen between each GPU in the same machine?

That's not how my tool works. You submit reports for a single device. If a system has two devices, a user can submit reports for both devices.

**Comment by tecanec** [comment]
> Not sure what you mean by "examinees" though. I don't examine anybody.

I'm refering to those who submit data. Perhaps "contributers" would be a better word? (Although that may signify something else here on Github.)

> Calculations like coverage is based on most recent data

So if someone stopped submitting during the 1.1 era, they'd show in the data as still using 1.1, whereas if they kept submitting until the 1.3 era, they'd only influence the data as 1.3 users today? Or do you track driver updates for their devices?

**Comment by SaschaWillems** [comment]
> I'm refering to those who submit data. Perhaps "contributers" would be a better word? (Although that may signify something else here on Github.)

Makes more sense. Data is uploaded using a client application. The application is available for free on Windows, Linux, Mac and Android. It also ships with the LunarG Vulkan SDK.

> So if someone stopped submitting during the 1.1 era, they'd show in the data as still using 1.1, whereas if they kept submitting until the 1.3 era, they'd only influence the data as 1.3 users today? Or do you track driver updates for their devices?

For device coverage, latest api version counts. So if an extension wasn't available for device X with driver Y, but was added in driver Z, the database will show that device as supported. That's why I don't need to delete old data.

**Comment by tecanec** [comment]
This is all very nice to know. Will this be detailed on the "about"-page?

> For device coverage, latest api version counts. So if an extension wasn't available for device X with driver Y, but was added in driver Z, the database will show that device as supported. That's why I don't need to delete old data.

I may be getting a bit sidetracked here, but would that not still include old hardware that has since been replaced and which does not support newer features?

**Comment by SaschaWillems** [comment]
> This is all very nice to know. Will this be detailed on the "about"-page?

Maybe at some point. I've been wanting to write some end-user documentation for the database, but haven't found the time yet.

> I may be getting a bit sidetracked here, but would that not still include old hardware that has since been replaced and which does not support newer features?

That's not the goal of the database. It's not like Steam's hardware survey that tells you about market share.

If you want to exclude "old" hardware (which in itself is a term that's hard to define) you can pre-filter from the topbar:
![image](https://github.com/SaschaWillems/vulkan.gpuinfo.org/assets/10283127/d58a0614-8a8d-4ff8-a53a-c46e3a8b4039)

That way, numbers won't include devices that don't support at least the version you select.

**Comment by tecanec** [comment]
> That's not the goal of the database. It's not like Steam's hardware survey that tells you about market share.

I mean since there's no need to support a graphics card that has reached its end of life.

**Comment by SaschaWillems** [comment]
> I mean since there's no need to support a graphics card that has reached its end of life.

There is no end of life for GPUs. Users are very reluctant to update. But then again, the database is not meant to check for GPU market share anyway.
