### ISSUE TITLE
Only 25 entries since commits from August, 15th

### ISSUE THREAD

**Issue by StefanG3D** [SaschaWillems/vulkan.gpuinfo.org#74]
For example check your own reports:

https://vulkan.gpuinfo.org/listreports.php?submitter=Sascha%20Willems

**Comment by SaschaWillems** [comment]
What's the actual issue?

**Comment by StefanG3D** [comment]
You cannot click "next" anymore if you submitted more than 25 reports.

**Comment by SaschaWillems** [comment]
Okay, so this is a navigation problem when the listing is filtered. Thanks for raising this issue, I'll take a look.

**Comment by SaschaWillems** [comment]
Should work as expected again. I was accidentally adding the pagination clause to the total count statement.
