### ISSUE TITLE
Instead of VkPhysicalDeviceDescriptorBufferPropertiesEXT in the report, its misreporting as VkPhysicalDeviceDescriptorBufferDensityMapPropertiesEXT 

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [SaschaWillems/vulkan.gpuinfo.org#76]
The whole of the issue has been described here (first wrongly accused the python script):
https://github.com/KhronosGroup/Vulkan-Profiles/issues/484

You might want to run the report through the profile validator before making its profile JSON downloadable.

Because it fails against the `.json` schema not only because of the name typo but also because some of the members are strings and not integers

**Comment by SaschaWillems** [comment]
> You might want to run the report through the profile validator before making its profile JSON downloadable.

That's sadly not that easy to a lot of different reasons.

Profile generation is already pretty much the most complex part of the back-end and adding schema validation would add even more complexity.

Tbh. I'm fine with the DB exporting JSONs that sometimes won't validate 100%. Esp. since I have to manually update and match the profile libraries.

**Comment by SaschaWillems** [comment]
Please test again, the generated profiles should now validate clean against the schema files.

Fixing this wasn't trivial and I took the opportunity to rewrite some important parts of the profile generation code and the way struct and type mappings are generated from the spec. Aside from fixing problems with invalid files this should make it easier for me to update to newer profile schema versions and should make generation more future proof.

**Comment by SaschaWillems** [comment]
Closing this for now. If the issue persists, please open a new issue.
