### ISSUE TITLE
Feature Request: readonly direct db queries

### ISSUE THREAD

**Issue by memory-thrasher** [SaschaWillems/vulkan.gpuinfo.org#77]
I love the ideas presented in [issue 16](https://github.com/SaschaWillems/vulkan.gpuinfo.org/issues/16) but I also know how much of a pain that is to implement. In the case of this product, it seems reasonable to me that many of the users are themselves developers, so likely have at least basic database skills. Protections can be implemented against malicious and inefficient queries with rate limiting, timeouts, captchas, and running the query from a dedicated read-only user.

My specific use case is I'd like a coverage of gpus that have at least one queue that supports all 3 basic queue types. That is a super niche that would be easy to implement as a one-off query, but I understand that I'm probably the only one who wants it, and some generic enough UI that allows any similarly complex queries to be requested would be quite difficult indeed. So I see an open query as a reasonable compromise: let the user who wants niche data do the work to query it.

**Comment by SaschaWillems** [comment]
There will never be a direct way to query the database for several reasons that I don't want or can't talk about in public.

I already provide APIs for database access and I'm looking into making this so generic, that you can query all the information that's safe for public usage. No ETA on that though.

**Comment by memory-thrasher** [comment]
Ok. Sounds like I'll be running a mirror fed by the api to support my queries. In order to update it without eating up both our bandwidth, I'd suggest a api endpoint meant to provide (the public portion of) reports newer than a given date.

**Comment by SaschaWillems** [comment]
That will be possible. The generic REST api will allow you to filter reports like this:

`API_ENDPOINT/reports?filter=submissiondate,gt,2023-01-01`

Which would only return reports submitted at or after this date.

**Comment by memory-thrasher** [comment]
perfect
