### ISSUE TITLE
maxPushDescriptors limit missing

### ISSUE THREAD

**Issue by hrydgard** [SaschaWillems/vulkan.gpuinfo.org#8]
The push descriptors extension adds a new limit, which isn't on the site:

VkPhysicalDevicePushDescriptorPropertiesKHR::maxPushDescriptors

**Comment by SaschaWillems** [comment]
There's no way to search for extended properties and features yet, but that'll be added at some point. No ETA though.

**Comment by hrydgard** [comment]
This seems to be present now with your latest update, so as far as I am concerned, this can be closed.
