### ISSUE TITLE
Mismatch between feature query results and the actual device report

### ISSUE THREAD

**Issue by Alegruz** [SaschaWillems/vulkan.gpuinfo.org#84]
According to the [Vulkan GPU Info website](https://vulkan.gpuinfo.org/listdevicescoverage.php?feature=shaderFloat64&platform=android)'s query results for Android devices that supports `shaderFeature64`,
Samsung's SM-S918U device shows up on the list.
However, on the [device's report](https://vulkan.gpuinfo.org/displayreport.php?id=24375#features), the feature is not supported.

I haven't checked if other features equally produce the same issue.

**Comment by SaschaWillems** [comment]
Thanks for reporting this. I can confirm this, and will look into it.

**Comment by SaschaWillems** [comment]
This should be fixed with the latest update. That device is no longer showing up in that listing.
