### ISSUE TITLE
Updating existing reports is broken

### ISSUE THREAD

**Issue by StefanG3D** [SaschaWillems/vulkan.gpuinfo.org#87]
Last successful update of an existing report i made was on 2024-02-14 19:49:50

Now i get a popup - _Error: The report could not be updated._

**Comment by SaschaWillems** [comment]
Can you save the json from the caps viewer and attach it here?

**Comment by StefanG3D** [comment]
Actually i wanted to update LLVMPIPE, but in the report i find only my iGPU
[noupdate.txt](https://github.com/SaschaWillems/vulkan.gpuinfo.org/files/14348571/noupdate.txt)

**Comment by StefanG3D** [comment]
Last time failed my own build under Windows.

Today i double-checked under Linux with the driver from [oibaf](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) - same failure
Looks like the new extension _VK_KHR_shader_maximal_reconvergence_ is the culprit
https://gitlab.freedesktop.org/mesa/mesa/-/commit/41b5ff46aadb8aa80d3d7956bac48a3bdd1fbf86

**Comment by StefanG3D** [comment]
Following report was from me using VK1.3.278
https://vulkan.gpuinfo.org/displayreport.php?id=28190
Afterwards i build llvmpipe from this MR
[lavapipe: Implement VK_KHR_ray_query](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/25616#top)
Then updating report failed

3 weeks ago i built llvmpipe from git with VK1.3.277 and uploaded the report
https://vulkan.gpuinfo.org/displayreport.php?id=27733
Then i built llvmpipe from the MR with VK_KHR_ray_query and was able to update the report

I will build new drivers after VK1.3.279 release and report back.

**Comment by SaschaWillems** [comment]
Thank you very much. With the changes to the upload script I should get a notification if updates fail from now on.
