### ISSUE TITLE
Enter surprisingly triggers compare

### ISSUE THREAD

**Issue by krOoze** [SaschaWillems/vulkan.gpuinfo.org#9]
Pressing Enter in any of the input fields triggers report compare.
Considering the nature of the "form", that is surprising. And annoying, as sometimes I (unnecessarily but) instinctively press Enter after writing the search term into the column filter boxes.

It would be great if it was possible to disable Enter there.

**Comment by SaschaWillems** [comment]
This should be fixed. That's just how HTML forms works, enter triggers submit, but I'm now catching the enter key to suppress this behavior.
