### ISSUE TITLE
Marking some extensions as "not expected to be supported by driver"

### ISSUE THREAD

**Issue by spencer-lunarg** [SaschaWillems/vulkan.gpuinfo.org#96]
There are some extension `VK_EXT_validation_features`, `VK_EXT_debug_utils`, `VK_EXT_layer_settings` that are not suppose to be implemented by the driver, but instead the loader/layers

This becomes an issue for people newer to Vulkan and mix the fact "gpuinfo says no one supports `VK_EXT_debug_utils` so I can't use it" vs "the driver itself doesn't do the work"

One idea was maybe having some asterisk or some UI marker to help mark these (or maybe remove from the display at all)

If you want to go ahead with this, I can gather all the "drivers aren't expected to implement it" extensions for you as well

**Comment by SaschaWillems** [comment]
It's something I noticed in the past, some drivers seem to report instance as device extensions. Esp. on Android.

I'm open for somehow excluding this, as long as it doesn't require a lot of manual intervention. So if it's e.g. a small list of extensions that doesn't change a lot I could add that as a table and simply hide those extensions from all SQL queries.

If you can provide such a list, I can start designing a solution.

**Comment by charles-lunarg** [comment]
VK_EXT_tooling_info comes to mind as well. And VK_EXT_debug_report/marker but those are deprecated so shouldn't warrant extra attention.

**Comment by spencer-lunarg** [comment]
`VK_EXT_validation_flags` as well

so I think the list so far is 

- `VK_EXT_layer_settings`
- `VK_EXT_validation_features`
- `VK_EXT_validation_flags`
- `VK_EXT_debug_utils`
- `VK_EXT_debug_report`
- `VK_EXT_debug_marker`

**Comment by SaschaWillems** [comment]
Looking at that list and the sadly large no. of reports that get this wrong the only option I see is putting those into a table and then exclude them from all coverage listing. I can then also use that to highlight those in the report detail view.

**Comment by Tobski** [comment]
The only other one I can think of is maybe VK_EXT_headless_surface, which I'm fairly sure is a layer implementation only?

**Comment by SaschaWillems** [comment]
Afaik it's also available as an instance extension (aside from the layer). But anyways, if a device reports it as a device extension, it's obviously wrong ;)

**Comment by SaschaWillems** [comment]
Some stats:

| Extension | Reports |
| - | - |
| VK_EXT_debug_marker	|  2123 | 
| VK_EXT_debug_report	|  189 | 
| VK_EXT_debug_utils	|  192 | 

No reports yet for the other extensions mentioned here. Will try to add a way to exclude those from results and highlight them in the reports with an upcoming update.

**Comment by SaschaWillems** [comment]
Quick note: VK_EXT_debug_marker is indeed a device extension, so I won't remove that one.

**Comment by SaschaWillems** [comment]
The database now does two things:

- The global device extension listing page will simply exclude instance extensions wrongly reported as device extensions
- Reports will add a note to instance extensions wrongly reported as device extensions (see e.g. https://vulkan.gpuinfo.org/displayreport.php?id=10674#extensions)

Extensions are managed using a blacklist table, so if you encounter other device extensions wrongly reported as instance extensions, drop me a line :)

**Comment by spencer-lunarg** [comment]
![image](https://github.com/user-attachments/assets/dc702bb4-f134-44e8-87fa-22e8283e0990)

This is awesome! Thanks @SaschaWillems !!
